# Analysis for Sacramento State DataFest 2025

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
leases_df = pd.read_csv('C:\\Users\\wolfe\\OneDrive\\Desktop\\asa-datafest-sac-state\\real-estate-data\\Leases.csv')
leases_df.head(20)

,year,quarter,monthsigned,market,building_name,building_id,address,region,city,state,...,overall_rent,direct_available_space,direct_availability_proportion,direct_internal_class_rent,direct_overall_rent,sublet_available_space,sublet_availability_proportion,sublet_internal_class_rent,sublet_overall_rent,leasing
0,2018,Q1,1.0,Atlanta,10 Glenlake North Tower,Atlanta_Central Perimeter_Atlanta_10 Glenlake ...,10 Glenlake Pky NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
1,2018,Q1,1.0,Atlanta,100 City View,Atlanta_Northwest_Atlanta_100 City View_3330 C...,3330 Cumberland Blvd,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
2,2018,Q1,1.0,Atlanta,1000 Parkwood,Atlanta_Northwest_Atlanta_1000 Parkwood_1000 P...,1000 Parkwood Cir SE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
3,2018,Q1,1.0,Atlanta,1100 Circle 75,Atlanta_Northwest_Atlanta_1100 Circle 75_1100 ...,1100 Circle 75 Pky SE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
4,2018,Q1,1.0,Atlanta,1200 Ashwood,Atlanta_Central Perimeter_Atlanta_1200 Ashwood...,1200 Ashwood Pky,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
5,2018,Q1,1.0,Atlanta,1200 Ashwood,Atlanta_Central Perimeter_Atlanta_1200 Ashwood...,1200 Ashwood Pky,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
6,2018,Q1,1.0,Atlanta,2 Sun,Atlanta_Northeast_Peachtree Corners_2 Sun_2 Su...,2 Sun Ct,South,Peachtree Corners,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
7,2018,Q1,1.0,Atlanta,200 Ashford Center North,Atlanta_Central Perimeter_Atlanta_200 Ashford ...,200 Ashford Ctr N,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
8,2018,Q1,1.0,Atlanta,271 17th,Atlanta_Midtown_Atlanta_271 17th_271 17th St NW,271 17th St NW,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
9,2018,Q1,1.0,Atlanta,271 17th,Atlanta_Midtown_Atlanta_271 17th_271 17th St NW,271 17th St NW,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
10,2018,Q1,1.0,Atlanta,311 Green Street,Atlanta_Northeast_Gainesville_311 Green Street...,311 Green St NW,South,Gainesville,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
11,2018,Q1,1.0,Atlanta,315 West Ponce,Atlanta_Northlake_Decatur_315 West Ponce_315 W...,315 W Ponce De Leon Ave,South,Decatur,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
12,2018,Q1,1.0,Atlanta,500 Northpark,Atlanta_Central Perimeter_Atlanta_500 Northpar...,1100 Abernathy Rd NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
13,2018,Q1,1.0,Atlanta,900 Circle 75,Atlanta_Northwest_Atlanta_900 Circle 75_900 Ci...,900 Circle 75 Pky SE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
14,2018,Q1,1.0,Atlanta,Bank of America Plaza,Atlanta_Downtown_Atlanta_Bank of America Plaza...,600 Peachtree St NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
15,2018,Q1,1.0,Atlanta,Bldg 1,Atlanta_Central Perimeter_Atlanta_Bldg 1_5825 ...,5825 Glenridge Dr NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
16,2018,Q1,1.0,Atlanta,Bldg 100,Atlanta_Northeast_Peachtree Corners_Bldg 100_3...,3850 Holcomb Bridge Rd,South,Peachtree Corners,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
17,2018,Q1,1.0,Atlanta,Bldg 17,Atlanta_Northlake_Atlanta_Bldg 17_17 Executive...,17 Executive Park Dr NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126.0
18,2018,Q1,1.0,Atlanta,Bldg 50,Atlanta_Northlake_Atlanta_Bldg 50_50 Executive...,50 Executive Park South NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0
19,2018,Q1,1.0,Atlanta,Bldg 57,Atlanta_Northlake_Atlanta_Bldg 57_57 Executive...,57 Executive Park Dr NE,South,Atlanta,GA,...,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742.0

In [8]:
leases_df.shape

(194685, 35)

In [6]:
leases_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194685 entries, 0 to 194684
Data columns (total 35 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   year                            194685 non-null  int64
 1   quarter                         194685 non-null  object
 2   monthsigned                     193822 non-null  float64
 3   market                          194685 non-null  object
 4   building_name                   157999 non-null  object
 5   building_id                     194685 non-null  object
 6   address                         194685 non-null  object
 7   region                          194685 non-null  object
 8   city                            194685 non-null  object
 9   state                           194685 non-null  object
 10  zip                             194684 non-null  float64
 11  internal_submarket              194685 non-null  object
 12  internal_class                  194676 non-null  object
 13  leasedSF                        194685 non-null  float64
 14  company_name                    37216 non-null   object
 15  internal_industry               26401 non-null   object
 16  transaction_type                194146 non-null  object
 17  internal_market_cluster         75838 non-null   object
 18  costarID                        194685 non-null  int64
 19  space_type                      187140 non-null  object
 20  CBD_suburban                    194685 non-null  object
 21  RBA                             145541 non-null  float64
 22  available_space                 145541 non-null  float64
 23  availability_proportion         145541 non-null  float64
 24  internal_class_rent             145541 non-null  float64
 25  overall_rent                    145541 non-null  float64
 26  direct_available_space          121674 non-null  float64
 27  direct_availability_proportion  121674 non-null  float64
 28  direct_internal_class_rent      121674 non-null  float64
 29  direct_overall_rent             121674 non-null  float64
 30  sublet_available_space          121674 non-null  float64
 31  sublet_availability_proportion  121674 non-null  float64
 32  sublet_internal_class_rent      121674 non-null  float64
 33  sublet_overall_rent             121674 non-null  float64
 34  leasing                         145541 non-null  float64
dtypes: float64(17), int64(2), object(16)
memory usage: 52.0+ MB

In [7]:
leases_df.isna().sum()

year                                   0
quarter                                0
monthsigned                          863
market                                 0
building_name                      36686
building_id                            0
address                                0
region                                 0
city                                   0
state                                  0
zip                                    1
internal_submarket                     0
internal_class                         9
leasedSF                               0
company_name                      157469
internal_industry                 168284
transaction_type                     539
internal_market_cluster           118847
costarID                               0
space_type                          7545
CBD_suburban                           0
RBA                                49144
available_space                    49144
availability_proportion            49144
internal_class_rent                49144
overall_rent                       49144
direct_available_space             73011
direct_availability_proportion     73011
direct_internal_class_rent         73011
direct_overall_rent                73011
sublet_available_space             73011
sublet_availability_proportion     73011
sublet_internal_class_rent         73011
sublet_overall_rent                73011
leasing                            49144
dtype: int64

In [11]:
leases_df.columns

Index(['year', 'quarter', 'monthsigned', 'market', 'building_name',
       'building_id', 'address', 'region', 'city', 'state', 'zip',
       'internal_submarket', 'internal_class', 'leasedSF', 'company_name',
       'internal_industry', 'transaction_type', 'internal_market_cluster',
       'costarID', 'space_type', 'CBD_suburban', 'RBA', 'available_space',
       'availability_proportion', 'internal_class_rent', 'overall_rent',
       'direct_available_space', 'direct_availability_proportion',
       'direct_internal_class_rent', 'direct_overall_rent',
       'sublet_available_space', 'sublet_availability_proportion',
       'sublet_internal_class_rent', 'sublet_overall_rent', 'leasing'],
      dtype='object')

In [12]:
columns_to_exclude = [
    'RBA', 'available_space', 'availability_proportion',
    'internal_class_rent', 'overall_rent',
    'direct_available_space', 'direct_availability_proportion',
    'direct_internal_class_rent', 'direct_overall_rent',
    'sublet_available_space', 'sublet_availability_proportion',
    'sublet_internal_class_rent', 'sublet_overall_rent'
]

leases_no_price_df = leases_df.drop(axis=1, columns=columns_to_exclude)
leases_no_price_df.head(20)

,year,quarter,monthsigned,market,building_name,building_id,address,region,city,state,...,internal_class,leasedSF,company_name,internal_industry,transaction_type,internal_market_cluster,costarID,space_type,CBD_suburban,leasing
0,2018,Q1,1.0,Atlanta,10 Glenlake North Tower,Atlanta_Central Perimeter_Atlanta_10 Glenlake ...,10 Glenlake Pky NE,South,Atlanta,GA,...,A,24736.0,Capital Investment Advisors,Financial Services and Insurance,Expansion,NaN,445509,Relet,Suburban,1205126.0
1,2018,Q1,1.0,Atlanta,100 City View,Atlanta_Northwest_Atlanta_100 City View_3330 C...,3330 Cumberland Blvd,South,Atlanta,GA,...,A,965.0,NaN,NaN,New,NaN,436994,Relet,Suburban,1205126.0
2,2018,Q1,1.0,Atlanta,1000 Parkwood,Atlanta_Northwest_Atlanta_1000 Parkwood_1000 P...,1000 Parkwood Cir SE,South,Atlanta,GA,...,A,2215.0,Efc Moen,NaN,New,NaN,434890,Relet,Suburban,1205126.0
3,2018,Q1,1.0,Atlanta,1100 Circle 75,Atlanta_Northwest_Atlanta_1100 Circle 75_1100 ...,1100 Circle 75 Pky SE,South,Atlanta,GA,...,O,1925.0,NaN,NaN,New,NaN,434720,Relet,Suburban,715742.0
4,2018,Q1,1.0,Atlanta,1200 Ashwood,Atlanta_Central Perimeter_Atlanta_1200 Ashwood...,1200 Ashwood Pky,South,Atlanta,GA,...,A,2404.0,NaN,NaN,New,NaN,437562,Relet,Suburban,1205126.0
5,2018,Q1,1.0,Atlanta,1200 Ashwood,Atlanta_Central Perimeter_Atlanta_1200 Ashwood...,1200 Ashwood Pky,South,Atlanta,GA,...,A,5091.0,NaN,NaN,New,NaN,437562,Relet,Suburban,1205126.0
6,2018,Q1,1.0,Atlanta,2 Sun,Atlanta_Northeast_Peachtree Corners_2 Sun_2 Su...,2 Sun Ct,South,Peachtree Corners,GA,...,A,13207.0,Kimley-Horn,"Construction, Engineering and Architecture",New,NaN,448077,Relet,Suburban,1205126.0
7,2018,Q1,1.0,Atlanta,200 Ashford Center North,Atlanta_Central Perimeter_Atlanta_200 Ashford ...,200 Ashford Ctr N,South,Atlanta,GA,...,A,1179.0,NaN,NaN,New,NaN,437704,Relet,Suburban,1205126.0
8,2018,Q1,1.0,Atlanta,271 17th,Atlanta_Midtown_Atlanta_271 17th_271 17th St NW,271 17th St NW,South,Atlanta,GA,...,A,3273.0,NaN,NaN,New,NaN,5993371,Relet,CBD,1205126.0
9,2018,Q1,1.0,Atlanta,271 17th,Atlanta_Midtown_Atlanta_271 17th_271 17th St NW,271 17th St NW,South,Atlanta,GA,...,A,15795.0,Square,"Technology, Advertising, Media, and Information",New,NaN,5993371,Relet,CBD,1205126.0
10,2018,Q1,1.0,Atlanta,311 Green Street,Atlanta_Northeast_Gainesville_311 Green Street...,311 Green St NW,South,Gainesville,GA,...,O,405.0,Velocity Technology Partners,NaN,New,NaN,516150,Relet,Suburban,715742.0
11,2018,Q1,1.0,Atlanta,315 West Ponce,Atlanta_Northlake_Decatur_315 West Ponce_315 W...,315 W Ponce De Leon Ave,South,Decatur,GA,...,O,404.0,NaN,NaN,New,NaN,437342,Relet,Suburban,715742.0
12,2018,Q1,1.0,Atlanta,500 Northpark,Atlanta_Central Perimeter_Atlanta_500 Northpar...,1100 Abernathy Rd NE,South,Atlanta,GA,...,A,12364.0,Trident Fund Services,NaN,New,NaN,441530,Relet,Suburban,1205126.0
13,2018,Q1,1.0,Atlanta,900 Circle 75,Atlanta_Northwest_Atlanta_900 Circle 75_900 Ci...,900 Circle 75 Pky SE,South,Atlanta,GA,...,O,4028.0,NaN,NaN,New,NaN,434795,Relet,Suburban,715742.0
14,2018,Q1,1.0,Atlanta,Bank of America Plaza,Atlanta_Downtown_Atlanta_Bank of America Plaza...,600 Peachtree St NE,South,Atlanta,GA,...,A,49914.0,Flexport,"Technology, Advertising, Media, and Information",Relocation,NaN,442458,Relet,CBD,1205126.0
15,2018,Q1,1.0,Atlanta,Bldg 1,Atlanta_Central Perimeter_Atlanta_Bldg 1_5825 ...,5825 Glenridge Dr NE,South,Atlanta,GA,...,O,3488.0,NaN,NaN,New,NaN,444492,Relet,Suburban,715742.0
16,2018,Q1,1.0,Atlanta,Bldg 100,Atlanta_Northeast_Peachtree Corners_Bldg 100_3...,3850 Holcomb Bridge Rd,South,Peachtree Corners,GA,...,O,1653.0,Winwell Logistics,NaN,New,NaN,446387,Relet,Suburban,715742.0
17,2018,Q1,1.0,Atlanta,Bldg 17,Atlanta_Northlake_Atlanta_Bldg 17_17 Executive...,17 Executive Park Dr NE,South,Atlanta,GA,...,A,477.0,NaN,NaN,New,NaN,437159,Relet,Suburban,1205126.0
18,2018,Q1,1.0,Atlanta,Bldg 50,Atlanta_Northlake_Atlanta_Bldg 50_50 Executive...,50 Executive Park South NE,South,Atlanta,GA,...,O,817.0,NaN,NaN,New,NaN,437164,Relet,Suburban,715742.0
19,2018,Q1,1.0,Atlanta,Bldg 57,Atlanta_Northlake_Atlanta_Bldg 57_57 Executive...,57 Executive Park Dr NE,South,Atlanta,GA,...,O,2724.0,NaN,NaN,New,NaN,41864,Relet,Suburban,715742.0

In [18]:
leases_nona_df = leases_df.dropna(axis=0)
leases_nona_df.head(20)

,year,quarter,monthsigned,market,building_name,building_id,address,region,city,state,...,overall_rent,direct_available_space,direct_availability_proportion,direct_internal_class_rent,direct_overall_rent,sublet_available_space,sublet_availability_proportion,sublet_internal_class_rent,sublet_overall_rent,leasing
7776,2019,Q1,1.0,Baltimore,Executive Park West,Baltimore_Baltimore County West_Windsor Mill_E...,3200 Lord Baltimore Dr,Northeast,Windsor Mill,MD,...,23.838594,5715274.0,0.0694,20.593518,23.901592,250994.0,0.0030,19.812714,23.045405,333096.0
7842,2019,Q1,1.0,Boston,65 Blue Sky Dr,Boston_Route 128 North_Burlington_65 Blue Sky ...,65 Network Dr,Northeast,Burlington,MA,...,29.911067,14555051.0,0.0580,39.616733,29.056201,3062962.0,0.0122,28.525612,26.273218,2054850.0
7875,2019,Q1,1.0,Boston,Oliver Street Tower,Boston_Financial District_Boston_Oliver Street...,125 High St,Northeast,Boston,MA,...,29.911067,14555051.0,0.0580,39.616733,29.056201,3062962.0,0.0122,28.525612,26.273218,2054850.0
7876,2019,Q1,1.0,Boston,One Beacon Ln,Boston_Route 128 South_Canton_One Beacon Ln_15...,150 Royall St,Northeast,Canton,MA,...,29.911067,13176365.0,0.0525,18.877410,29.056201,1151648.0,0.0046,20.941226,26.273218,1219157.0
7899,2019,Q1,1.0,Boston,Tower at Northwoods,Boston_Route 128 North_Danvers_Tower at Northw...,222 Rosewood Dr,Northeast,Danvers,MA,...,29.911067,14555051.0,0.0580,39.616733,29.056201,3062962.0,0.0122,28.525612,26.273218,2054850.0
8876,2019,Q1,1.0,Los Angeles,Bldg A,Los Angeles_South Bay_Torrance_Bldg A_2355 Cre...,2355 Crenshaw Blvd,West,Torrance,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
8877,2019,Q1,1.0,Los Angeles,Bldg A,Los Angeles_South Bay_Torrance_Bldg A_2355 Cre...,2355 Crenshaw Blvd,West,Torrance,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
8896,2019,Q1,1.0,Los Angeles,Century Park East,Los Angeles_Century City_Los Angeles_Century P...,1888 Century Park E,West,Los Angeles,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
8932,2019,Q1,1.0,Los Angeles,Lantana Center,Los Angeles_Santa Monica_Santa Monica_Lantana ...,3000 W Olympic Blvd,West,Santa Monica,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
8943,2019,Q1,1.0,Los Angeles,One Westside,Los Angeles_Westwood/West LA_Los Angeles_One W...,10800-10900 W Pico Blvd,West,Los Angeles,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
8944,2019,Q1,1.0,Los Angeles,One World Trade Center,Los Angeles_Long Beach_Long Beach_One World Tr...,1 World Trade Ctr,West,Long Beach,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
8954,2019,Q1,1.0,Los Angeles,Phase II,Los Angeles_Santa Monica_Santa Monica_Phase II...,2450 Colorado Ave,West,Santa Monica,CA,...,38.947765,21331331.0,0.0996,42.208543,39.550654,2995919.0,0.0140,35.495420,34.392686,3506703.0
9117,2019,Q1,1.0,Manhattan,10 Grand Central,Manhattan_Grand Central_New York_10 Grand Cent...,155 E 44th St,Northeast,New York,NY,...,77.806433,22724341.0,0.0508,91.083837,80.505624,5654699.0,0.0126,61.429178,59.319707,5136768.0
9119,2019,Q1,1.0,Manhattan,100104 Fifth Avenue,Manhattan_Flatiron_New York_100104 Fifth Avenu...,100-104 5th Ave,Northeast,New York,NY,...,77.806433,14984686.0,0.0335,62.291501,80.505624,4083843.0,0.0091,55.958021,59.319707,3615343.0
9120,2019,Q1,1.0,Manhattan,100106 18th St,Manhattan_Union Square_New York_100106 18th St...,215 Park Ave S,Northeast,New York,NY,...,77.806433,14984686.0,0.0335,62.291501,80.505624,4083843.0,0.0091,55.958021,59.319707,3615343.0
9122,2019,Q1,1.0,Manhattan,107113 Crosby St,Manhattan_Soho_New York_107113 Crosby St_270 L...,270 Lafayette St,Northeast,New York,NY,...,77.806433,14984686.0,0.0335,62.291501,80.505624,4083843.0,0.0091,55.958021,59.319707,3615343.0
9124,2019,Q1,1.0,Manhattan,110 E 24th St,Manhattan_Park Avenue South_New York_110 E 24t...,315 Park Ave S,Northeast,New York,NY,...,77.806433,14984686.0,0.0335,62.291501,80.505624,4083843.0,0.0091,55.958021,59.319707,3615343.0
9128,2019,Q1,1.0,Manhattan,112 W 34th St,Manhattan_Penn Plaza/Times Square South_New Yo...,111 W 33rd St,Northeast,New York,NY,...,77.806433,14984686.0,0.0335,62.291501,80.505624,4083843.0,0.0091,55.958021,59.319707,3615343.0
9129,2019,Q1,1.0,Manhattan,1127 E 53rd St,Manhattan_Plaza South_New York_1127 E 53rd St_...,520 Madison Ave,Northeast,New York,NY,...,77.806433,22724341.0,0.0508,91.083837,80.505624,5654699.0,0.0126,61.429178,59.319707,5136768.0
9137,2019,Q1,1.0,Manhattan,133135 E 52nd St,Manhattan_East Side / UN_New York_133135 E 52n...,600 Lexington Ave,Northeast,New York,NY,...,77.806433,22724341.0,0.0508,91.083837,80.505624,5654699.0,0.0126,61.429178,59.319707,5136768.0

In [13]:
prices_df = pd.read_csv('C:\\Users\\wolfe\\OneDrive\\Desktop\\asa-datafest-sac-state\\real-estate-data\\price-and-availability.csv')
prices_df.head(20)

,year,quarter,market,internal_class,RBA,available_space,availability_proportion,internal_class_rent,overall_rent,direct_available_space,direct_availability_proportion,direct_internal_class_rent,direct_overall_rent,sublet_available_space,sublet_availability_proportion,sublet_internal_class_rent,sublet_overall_rent,leasing
0,2018,Q1,Atlanta,A,101140416,20239067,0.200109,27.655891,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205126
1,2018,Q1,Atlanta,O,65810449,12728989,0.193419,18.560886,24.345689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,715742
2,2018,Q1,Austin,A,36815073,4281986,0.116311,40.384706,36.596618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1738905
3,2018,Q1,Austin,O,27947525,3360936,0.121082,30.118658,36.596618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185674
4,2018,Q1,Baltimore,A,41033288,6813380,0.166045,27.104835,22.954034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380750
5,2018,Q1,Baltimore,O,40265706,6531089,0.162200,20.120990,22.954034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,247089
6,2018,Q1,Boston,A,133073672,17127987,0.128711,42.297880,32.409956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2285080
7,2018,Q1,Boston,O,116186937,14486098,0.124679,20.147725,32.409956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,934610
8,2018,Q1,Charlotte,A,35441291,5603221,0.158099,28.589370,26.037735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1130188
9,2018,Q1,Charlotte,O,27835480,3019728,0.108485,20.755558,26.037735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,172401
10,2018,Q1,Chicago Suburbs,A,54362692,14511067,0.266931,26.326973,23.144766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,645808
11,2018,Q1,Chicago Suburbs,O,46619476,12280805,0.263426,19.606686,23.144766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,495329
12,2018,Q1,Dallas-Ft. Worth,A,121184708,30083227,0.248243,26.209930,24.063057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1818846
13,2018,Q1,Dallas-Ft. Worth,O,83574408,20321410,0.243154,20.940649,24.063057,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1241663
14,2018,Q1,Denver-Boulder,A,53002807,10646654,0.200870,30.393523,27.477139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1217038
15,2018,Q1,Denver-Boulder,O,57367634,9809072,0.170986,24.563433,27.477139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,865991
16,2018,Q1,Detroit,A,34423167,6565982,0.190743,20.998187,18.749409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,435687
17,2018,Q1,Detroit,O,47275239,9751490,0.206271,16.957171,18.749409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,396490
18,2018,Q1,Downtown Chicago,A,65660615,10070387,0.153370,44.876725,39.949176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1990909
19,2018,Q1,Downtown Chicago,O,72516822,11691293,0.161222,34.913855,39.949176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1351932

In [14]:
prices_df.shape

(1680, 18)

In [15]:
prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   year                            1680 non-null   int64
 1   quarter                         1680 non-null   object
 2   market                          1680 non-null   object
 3   internal_class                  1680 non-null   object
 4   RBA                             1680 non-null   int64
 5   available_space                 1680 non-null   int64
 6   availability_proportion         1680 non-null   float64
 7   internal_class_rent             1680 non-null   float64
 8   overall_rent                    1680 non-null   float64
 9   direct_available_space          1380 non-null   float64
 10  direct_availability_proportion  1380 non-null   float64
 11  direct_internal_class_rent      1380 non-null   float64
 12  direct_overall_rent             1380 non-null   float64
 13  sublet_available_space          1380 non-null   float64
 14  sublet_availability_proportion  1380 non-null   float64
 15  sublet_internal_class_rent      1380 non-null   float64
 16  sublet_overall_rent             1380 non-null   float64
 17  leasing                         1680 non-null   int64
dtypes: float64(11), int64(4), object(3)
memory usage: 236.4+ KB

In [16]:
prices_df.isna().sum()

year                                0
quarter                             0
market                              0
internal_class                      0
RBA                                 0
available_space                     0
availability_proportion             0
internal_class_rent                 0
overall_rent                        0
direct_available_space            300
direct_availability_proportion    300
direct_internal_class_rent        300
direct_overall_rent               300
sublet_available_space            300
sublet_availability_proportion    300
sublet_internal_class_rent        300
sublet_overall_rent               300
leasing                             0
dtype: int64

In [17]:
prices_nona_df = prices_df.dropna(axis=1)
prices_nona_df.head(20)

,year,quarter,market,internal_class,RBA,available_space,availability_proportion,internal_class_rent,overall_rent,leasing
0,2018,Q1,Atlanta,A,101140416,20239067,0.200109,27.655891,24.345689,1205126
1,2018,Q1,Atlanta,O,65810449,12728989,0.193419,18.560886,24.345689,715742
2,2018,Q1,Austin,A,36815073,4281986,0.116311,40.384706,36.596618,1738905
3,2018,Q1,Austin,O,27947525,3360936,0.121082,30.118658,36.596618,185674
4,2018,Q1,Baltimore,A,41033288,6813380,0.166045,27.104835,22.954034,380750
5,2018,Q1,Baltimore,O,40265706,6531089,0.162200,20.120990,22.954034,247089
6,2018,Q1,Boston,A,133073672,17127987,0.128711,42.297880,32.409956,2285080
7,2018,Q1,Boston,O,116186937,14486098,0.124679,20.147725,32.409956,934610
8,2018,Q1,Charlotte,A,35441291,5603221,0.158099,28.589370,26.037735,1130188
9,2018,Q1,Charlotte,O,27835480,3019728,0.108485,20.755558,26.037735,172401
10,2018,Q1,Chicago Suburbs,A,54362692,14511067,0.266931,26.326973,23.144766,645808
11,2018,Q1,Chicago Suburbs,O,46619476,12280805,0.263426,19.606686,23.144766,495329
12,2018,Q1,Dallas-Ft. Worth,A,121184708,30083227,0.248243,26.209930,24.063057,1818846
13,2018,Q1,Dallas-Ft. Worth,O,83574408,20321410,0.243154,20.940649,24.063057,1241663
14,2018,Q1,Denver-Boulder,A,53002807,10646654,0.200870,30.393523,27.477139,1217038
15,2018,Q1,Denver-Boulder,O,57367634,9809072,0.170986,24.563433,27.477139,865991
16,2018,Q1,Detroit,A,34423167,6565982,0.190743,20.998187,18.749409,435687
17,2018,Q1,Detroit,O,47275239,9751490,0.206271,16.957171,18.749409,396490
18,2018,Q1,Downtown Chicago,A,65660615,10070387,0.153370,44.876725,39.949176,1990909
19,2018,Q1,Downtown Chicago,O,72516822,11691293,0.161222,34.913855,39.949176,1351932